language: python
matrix:
  include:
    - python: "3.4"
      env: TASK=py34

    - python: "3.5"
      env: TASK=py35

    - python: "3.6"
      env: TASK=py36

before_install:
  - "pip install coveralls tox"

script:
  - "tox -e $TASK"

after_success:
  - if [ "$TASK" == "py36" ]; then coveralls; fi

deploy:
    provider: pypi
    user: "alcarney"
    on:
        condition: $TASK = py36
        python: 3.6
    secure: "LtV1WAArEQw/jum539onAorszYbqQydO5nHXB6k9njqoX9OvkvalIJ2stFqayIt4UDcyhTxJs/qPnFFfD7SK65iipFkiZ+9E3x7BtHzl6vumg8i5/KEI3Bisy+bCo+CdtJV4OuVhrR4rjkalBlHjengR5dG45Ic3RYi089ZY0Y2sVfnMe0RNJTPkQ9WAo1k/T+QpS9uNSXX7ZiBAuyvnfAMurN3r8wDsItPtVNH6UHogKTC6hYjGCGsZyYEevsGCb/30c3E0ZnVfiqrl3WapgwdwvObc/fZKTx3gjM9qNuZMPmg9t3q5DFtUedDtQ8zY7Y6ldXsgwZ0xNHj+2Y3Fd3GtxmxDPF/nR0yw56S3Zz1ARN/7ERXeAlC9uddUoVbjsybYfaZhaoUPGY/zGdMViex6dk63JfDTxgGohJzmuOYu5FrsMLSccF72pcnexGuAci2ngi3nJlp5iDZ/yCT5ruhvqrLJ5JahZTWT51Va/aOWSt7j3QXpZeXziijcJj6jiKEDWmaPXychBBOU6+1vKnnYxP7SDIGk6Wc5vL6LLqtSJzZc3S3RMC7Vtsui0GKmXXGXNGUemzd5C9gHUiaWeUjZWfQweuXXkE8ahaot+dxKxcRQ81l/KT14qDPmvHzllCeLx0IeSgbZD3UjZ84OxcdNNMErRoA8b/2KLjGE/9g="
